### ISSUE TITLE
md-style not applied

### ISSUE THREAD

**Issue by liudonghua123** [rianadon/shellinabox-md-style#1]
I replaced `00+Black on White.css` on `/etc/shellinabox/options-enabled/`. But it didn't work as expected!

However I can make it work by append `--css` options like belows.
```
shellinaboxd -t -s /cling:ldh:ldh:HOME:/home/ldh/miniconda3/bin/cling -p 4201 --css "`pwd`/00+Black on White.css"
```

**Comment by rianadon** [comment]
Thanks for the notice @liudonghua123! And for opening the first issue here :grin:.
Glad you found a way to make it work!

It's been a while since I've used shellinabox so something could've changed there. Anyways I'll update the readme to reflect your fix.

Thanks again!
